//CREATING DATABASE
CREATE DATABASE IF NOT EXISTS HOTEL_DB

//CREATING FILE FORMAT
CREATE OR REPLACE FILE FORMAT FF_CSV
    TYPE= 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY= '"'
    SKIP_HEADER= 1
    NULL_IF= ('NULL', 'null', '');

//CREATING STAGE
CREATE OR REPLACE STAGE HOTEL_BOOKING_STAGE
    FILE_FORMAT= FF_CSV;

//CREATING BRONZE TABLE

CREATE OR REPLACE TABLE hotel_bronze(
    booking_id STRING,
    hotel_id STRING,
    hotel_city STRING,
    customer_id STRING,
    customer_name STRING,  
    customer_email STRING,
    check_in_date DATE,
    check_out_date DATE ,
    room_type STRING,
    num_guests INT,
    total_amount INT,
    currency STRING,
    booking_status STRING
);

//COPYING DATA INTO BRONZE TABLE	

COPY INTO hotel_bronze
FROM @HOTEL_BOOKING_STAGE
FILE_FORMAT= (FORMAT_NAME= FF_CSV)
ON_ERROR= 'CONTINUE';

//QUERYING DATA
SELECT *
FROM hotel_bronze

//CHECKING DUPLICATES
SELECT COUNT(DISTINCT(BOOKING_ID))
FROM hotel_bronze

//CHECKING & REMOVING FOR DUPLICATES IN BOOKING ID
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn>1

//CLEANING SILVER
SELECT 
    BOOKING_ID,
    CASE WHEN HOTEL_ID IS NULL THEN 'N/A'
         ELSE HOTEL_ID
         END AS HOTEL_ID,
    CASE WHEN HOTEL_CITY IS NULL THEN 'N/A'
         ELSE TRIM(HOTEL_CITY)
         END AS HOTEL_CITY,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'N/A'
         ELSE CUSTOMER_ID
         END AS CUSTOMER_ID,
    CASE WHEN CUSTOMER_NAME IS NULL THEN 'N/A'
         ELSE TRIM(CUSTOMER_NAME)
         END AS CUSTOMER_NAME,
    CASE WHEN CUSTOMER_EMAIL = 'invalid-email'  THEN 'N/A'
         ELSE CUSTOMER_EMAIL
         END AS CUSTOMER_EMAIL,
    TRY_TO_DATE(CHECK_IN_DATE) AS CHECK_IN_DATE,
    TRY_TO_DATE(CHECK_OUT_DATE) AS CHECK_OUT_DATE,
     CASE WHEN ROOM_TYPE IS NULL  THEN 'N/A'
         ELSE TRIM(ROOM_TYPE)
         END AS ROOM_TYPE,
    NUM_GUESTS,
    ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) as TOTAL_AMOUNT,
    CASE WHEN CURRENCY IS NULL THEN 'N/A'
         ELSE TRIM(CURRENCY)
         END AS CURRENCY,
    CASE WHEN BOOKING_STATUS= 'Confirmeeed' THEN 'Confirmed'
         WHEN BOOKING_STATUS IS NULL THEN 'N/A'
         ELSE TRIM(BOOKING_STATUS)
         END AS BOOKING_STATUS,
    MONTHNAME(CHECK_IN_DATE) AS Month,
    EXTRACT(YEAR FROM CHECK_IN_DATE) AS Year,
FROM(
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn=1
)
WHERE TRY_TO_DATE(CHECK_OUT_DATE) >= TRY_TO_DATE(CHECK_IN_DATE)

//CREATING SILVER TABLE
CREATE OR REPLACE TABLE hotel_silver(
    booking_id STRING,
    hotel_id STRING,
    hotel_city STRING,
    customer_id STRING,
    customer_name STRING,  
    customer_email STRING,
    check_in_date DATE,
    check_out_date DATE ,
    room_type STRING,
    num_guests INT,
    total_amount INT,
    currency STRING,
    booking_status STRING,
    booking_month STRING,
    booking_year STRING
)

//INSERTING DATA INTO SILVER TABLE
INSERT INTO hotel_silver
SELECT 
    BOOKING_ID,
    CASE WHEN HOTEL_ID IS NULL THEN 'N/A'
         ELSE HOTEL_ID
         END AS HOTEL_ID,
    CASE WHEN HOTEL_CITY IS NULL THEN 'N/A'
         ELSE TRIM(HOTEL_CITY)
         END AS HOTEL_CITY,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'N/A'
         ELSE CUSTOMER_ID
         END AS CUSTOMER_ID,
    CASE WHEN CUSTOMER_NAME IS NULL THEN 'N/A'
         ELSE TRIM(CUSTOMER_NAME)
         END AS CUSTOMER_NAME,
    CASE WHEN CUSTOMER_EMAIL = 'invalid-email'  THEN 'N/A'
         ELSE CUSTOMER_EMAIL
         END AS CUSTOMER_EMAIL,
    TRY_TO_DATE(CHECK_IN_DATE) AS CHECK_IN_DATE,
    TRY_TO_DATE(CHECK_OUT_DATE) AS CHECK_OUT_DATE,
     CASE WHEN ROOM_TYPE IS NULL  THEN 'N/A'
         ELSE TRIM(ROOM_TYPE)
         END AS ROOM_TYPE,
    NUM_GUESTS,
    ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) as TOTAL_AMOUNT,
    CASE WHEN CURRENCY IS NULL THEN 'N/A'
         ELSE TRIM(CURRENCY)
         END AS CURRENCY,
    CASE WHEN BOOKING_STATUS= 'Confirmeeed' THEN 'Confirmed'
         WHEN BOOKING_STATUS IS NULL THEN 'N/A'
         ELSE TRIM(BOOKING_STATUS)
         END AS BOOKING_STATUS,
    MONTHNAME(CHECK_IN_DATE) AS Month,
    EXTRACT(YEAR FROM CHECK_IN_DATE) AS Year
    
FROM(
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn=1
)
WHERE TRY_TO_DATE(CHECK_OUT_DATE) >= TRY_TO_DATE(CHECK_IN_DATE);

//GOLD PROCESSING

CREATE VIEW hotel_main_gold AS
SELECT 
    BOOKING_ID,
    CASE WHEN HOTEL_ID IS NULL THEN 'N/A'
         ELSE HOTEL_ID
         END AS HOTEL_ID,
    CASE WHEN HOTEL_CITY IS NULL THEN 'N/A'
         ELSE TRIM(HOTEL_CITY)
         END AS HOTEL_CITY,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'N/A'
         ELSE CUSTOMER_ID
         END AS CUSTOMER_ID,
    CASE WHEN CUSTOMER_NAME IS NULL THEN 'N/A'
         ELSE TRIM(CUSTOMER_NAME)
         END AS CUSTOMER_NAME,
    CASE WHEN CUSTOMER_EMAIL = 'invalid-email'  THEN 'N/A'
         ELSE CUSTOMER_EMAIL
         END AS CUSTOMER_EMAIL,
    TRY_TO_DATE(CHECK_IN_DATE) AS CHECK_IN_DATE,
    TRY_TO_DATE(CHECK_OUT_DATE) AS CHECK_OUT_DATE,
     CASE WHEN ROOM_TYPE IS NULL  THEN 'N/A'
         ELSE TRIM(ROOM_TYPE)
         END AS ROOM_TYPE,
    NUM_GUESTS,
    ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) as TOTAL_AMOUNT,
    CASE WHEN CURRENCY IS NULL THEN 'N/A'
         ELSE TRIM(CURRENCY)
         END AS CURRENCY,
    CASE WHEN BOOKING_STATUS= 'Confirmeeed' THEN 'Confirmed'
         WHEN BOOKING_STATUS IS NULL THEN 'N/A'
         ELSE TRIM(BOOKING_STATUS)
         END AS BOOKING_STATUS,
    MONTHNAME(CHECK_IN_DATE) AS Month,
    EXTRACT(YEAR FROM CHECK_IN_DATE) AS Year
    
FROM(
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn=1
)
WHERE TRY_TO_DATE(CHECK_OUT_DATE) >= TRY_TO_DATE(CHECK_IN_DATE);

SELECT DISTINCT(currency)
FROM hotel_main_gold

//MONTHLY BOOKING
CREATE VIEW gold_montly_booking AS
SELECT MONTH AS MONTH,
       COUNT(*) AS monthly_booking,
FROM hotel_main_gold
GROUP BY MONTH
ORDER BY monthly_booking DESC

//MONTHLY REVENUE USD
SELECT MONTH AS MONTH,
       COUNT(*) AS NO_OF_USD_PAYMENTS,
       SUM(TOTAL_AMOUNT) AS TOTAL_USD
FROM hotel_main_gold
WHERE CURRENCY= 'USD'
GROUP BY MONTH
ORDER BY TOTAL_USD DESC

//MONTHLY REVENUE EUR
SELECT MONTH AS MONTH,
       COUNT(*) AS NO_OF_EUR_PAYMENTS,
       SUM(TOTAL_AMOUNT) AS TOTAL_EUR
FROM hotel_main_gold
WHERE CURRENCY= 'EUR'
GROUP BY MONTH
ORDER BY TOTAL_EUR DESC

//MONTHLY REVENUE INR
SELECT MONTH AS MONTH,
       COUNT(*) AS NO_OF_INR_PAYMENTS,
       SUM(TOTAL_AMOUNT) AS TOTAL_INR
FROM hotel_main_gold
WHERE CURRENCY= 'INR'
GROUP BY MONTH
ORDER BY TOTAL_INR DESC

//Combined monthly revenue

SELECT MONTH AS MONTH,
       YEAR AS YEAR,
       CURRENCY AS CURRENCY,
       SUM(TOTAL_AMOUNT) AS TOTAL_INR
FROM hotel_main_gold
GROUP BY 1,2,3
ORDER BY 1,2


//Overview of booking status
SELECT BOOKING_STATUS,
       COUNT(*) AS No_of_bookings
FROM hotel_main_gold
GROUP BY BOOKING_STATUS
ORDER BY No_of_bookings DESC

//Analysing month with most cancellation
SELECT BOOKING_STATUS,
       MONTH AS MONTH,
       YEAR AS YEAR,
       COUNT(*) AS No_of_bookings
FROM hotel_main_gold
WHERE BOOKING_STATUS='Cancelled'
GROUP BY 1,2,3
ORDER BY 4 DESC

//ROOM TYPE SUMMARY
SELECT ROOM_TYPE,
       COUNT(*) AS No_of_bookings
FROM hotel_main_gold
GROUP BY ROOM_TYPE
ORDER BY 2 DESC

//ROOM TYPE BY BOOKING STATUS
SELECT ROOM_TYPE AS ROOM_TYPE,
       BOOKING_STATUS AS BOOKING_STATUS,
       COUNT(*) AS No_of_bookings
FROM hotel_main_gold
WHERE BOOKING_STATUS='Cancelled'
GROUP BY 1,2
ORDER BY 3 DESC





