//CREATING DATABASE
CREATE DATABASE IF NOT EXISTS HOTEL_DB

//CREATING FILE FORMAT
CREATE OR REPLACE FILE FORMAT FF_CSV
    TYPE= 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY= '"'
    SKIP_HEADER= 1
    NULL_IF= ('NULL', 'null', '');

//CREATING STAGE
CREATE OR REPLACE STAGE HOTEL_BOOKING_STAGE
    FILE_FORMAT= FF_CSV;

//CREATING BRONZE TABLE

CREATE OR REPLACE TABLE hotel_bronze(
    booking_id STRING,
    hotel_id STRING,
    hotel_city STRING,
    customer_id STRING,
    customer_name STRING,  
    customer_email STRING,
    check_in_date DATE,
    check_out_date DATE ,
    room_type STRING,
    num_guests INT,
    total_amount INT,
    currency STRING,
    booking_status STRING
);

//COPYING DATA INTO BRONZE TABLE	

COPY INTO hotel_bronze
FROM @HOTEL_BOOKING_STAGE
FILE_FORMAT= (FORMAT_NAME= FF_CSV)
ON_ERROR= 'CONTINUE';

//QUERYING DATA
SELECT *
FROM hotel_bronze

//CHECKING DUPLICATES
SELECT COUNT(DISTINCT(BOOKING_ID))
FROM hotel_bronze

//CHECKING & REMOVING FOR DUPLICATES IN BOOKING ID
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn>1

//CLEANING SILVER
SELECT 
    BOOKING_ID,
    CASE WHEN HOTEL_ID IS NULL THEN 'N/A'
         ELSE HOTEL_ID
         END AS HOTEL_ID,
    CASE WHEN HOTEL_CITY IS NULL THEN 'N/A'
         ELSE TRIM(HOTEL_CITY)
         END AS HOTEL_CITY,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'N/A'
         ELSE CUSTOMER_ID
         END AS CUSTOMER_ID,
    CASE WHEN CUSTOMER_NAME IS NULL THEN 'N/A'
         ELSE TRIM(CUSTOMER_NAME)
         END AS CUSTOMER_NAME,
    CASE WHEN CUSTOMER_EMAIL = 'invalid-email'  THEN 'N/A'
         ELSE CUSTOMER_EMAIL
         END AS CUSTOMER_EMAIL,
    TRY_TO_DATE(CHECK_IN_DATE) AS CHECK_IN_DATE,
    TRY_TO_DATE(CHECK_OUT_DATE) AS CHECK_OUT_DATE,
     CASE WHEN ROOM_TYPE IS NULL  THEN 'N/A'
         ELSE TRIM(ROOM_TYPE)
         END AS ROOM_TYPE,
    NUM_GUESTS,
    ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) as TOTAL_AMOUNT,
    CASE WHEN CURRENCY IS NULL THEN 'N/A'
         ELSE TRIM(CURRENCY)
         END AS CURRENCY,
    CASE WHEN BOOKING_STATUS= 'Confirmeeed' THEN 'Confirmed'
         WHEN BOOKING_STATUS IS NULL THEN 'N/A'
         ELSE TRIM(BOOKING_STATUS)
         END AS BOOKING_STATUS,
    MONTHNAME(CHECK_IN_DATE) AS Month,
    EXTRACT(YEAR FROM CHECK_IN_DATE) AS Year,
FROM(
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn=1
)
WHERE TRY_TO_DATE(CHECK_OUT_DATE) >= TRY_TO_DATE(CHECK_IN_DATE)

//CREATING SILVER TABLE
CREATE OR REPLACE TABLE hotel_silver(
    booking_id STRING,
    hotel_id STRING,
    hotel_city STRING,
    customer_id STRING,
    customer_name STRING,  
    customer_email STRING,
    check_in_date DATE,
    check_out_date DATE ,
    room_type STRING,
    num_guests INT,
    total_amount INT,
    currency STRING,
    booking_status STRING,
    booking_month STRING,
    booking_year STRING
)

//INSERTING DATA INTO SILVER TABLE
INSERT INTO hotel_silver
SELECT 
    BOOKING_ID,
    CASE WHEN HOTEL_ID IS NULL THEN 'N/A'
         ELSE HOTEL_ID
         END AS HOTEL_ID,
    CASE WHEN HOTEL_CITY IS NULL THEN 'N/A'
         ELSE TRIM(HOTEL_CITY)
         END AS HOTEL_CITY,
    CASE WHEN CUSTOMER_ID IS NULL THEN 'N/A'
         ELSE CUSTOMER_ID
         END AS CUSTOMER_ID,
    CASE WHEN CUSTOMER_NAME IS NULL THEN 'N/A'
         ELSE TRIM(CUSTOMER_NAME)
         END AS CUSTOMER_NAME,
    CASE WHEN CUSTOMER_EMAIL = 'invalid-email'  THEN 'N/A'
         ELSE CUSTOMER_EMAIL
         END AS CUSTOMER_EMAIL,
    TRY_TO_DATE(CHECK_IN_DATE) AS CHECK_IN_DATE,
    TRY_TO_DATE(CHECK_OUT_DATE) AS CHECK_OUT_DATE,
     CASE WHEN ROOM_TYPE IS NULL  THEN 'N/A'
         ELSE TRIM(ROOM_TYPE)
         END AS ROOM_TYPE,
    NUM_GUESTS,
    ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) as TOTAL_AMOUNT,
    CASE WHEN CURRENCY IS NULL THEN 'N/A'
         ELSE TRIM(CURRENCY)
         END AS CURRENCY,
    CASE WHEN BOOKING_STATUS= 'Confirmeeed' THEN 'Confirmed'
         WHEN BOOKING_STATUS IS NULL THEN 'N/A'
         ELSE TRIM(BOOKING_STATUS)
         END AS BOOKING_STATUS,
    MONTHNAME(CHECK_IN_DATE) AS Month,
    EXTRACT(YEAR FROM CHECK_IN_DATE) AS Year
    
FROM(
SELECT *,
       ROW_NUMBER() OVER(PARTITION BY BOOKING_ID ORDER BY CHECK_IN_DATE DESC) AS rn
FROM hotel_bronze
QUALIFY rn=1
)
WHERE TRY_TO_DATE(CHECK_OUT_DATE) >= TRY_TO_DATE(CHECK_IN_DATE);












